### ISSUE TITLE
Error Installing schedcat with make

### ISSUE THREAD

**Issue by chen116** [brandenburg/schedcat#6]
Hi, 

when I do "make", I got the error message shown below:

In file included from src/testmain.cpp:22:0:
include/linprog/solver.h:32:2: error: #warning No LP solver available. [-Werror=cpp]

I have installed libgmp3c2, libgmp3-dev, libgmpxx4ldbl and swig

my g++ version is :gcc version 4.6.3 (Ubuntu/Linaro 4.6.3-1ubuntu5) 

my machine version:

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=12.04
DISTRIB_CODENAME=precise
DISTRIB_DESCRIPTION="Ubuntu 12.04.4 LTS"
NAME="Ubuntu"
VERSION="12.04.4 LTS, Precise Pangolin"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu precise (12.04.4 LTS)"
VERSION_ID="12.04"

Please let you know if you can help, thx!

Victor

**Comment by brandenburg** [comment]
Hi Victor,

`libgmp` is the GNU arbitrary precision math library and does not come with an LP solver. You need to install either GLPK (open source) or CPLEX (commercial). Ubuntu has packages for GLPK. I hope that helps. 

Best regards,
Björn

**Comment by chen116** [comment]
Thank you very much! it works! 

and for other people who has the same issue as me, after installing GLPK, I also need to run apt-get install python-dev. 

Thanks again!!
