### ISSUE TITLE
Inform about the need of a LP solver in the Readme

### ISSUE THREAD

**Issue by oliverpool** [brandenburg/schedcat#7]
Hi,

I searched for some hours why the `lp_analysis.py` file was missing from my installation, and I found out that it requires a [LP solver](https://github.com/brandenburg/schedcat/blob/4cb48348692c4f835194f43a38bfe721474ed794/native/Makefile#L128) (either cplex or glpk - that is freely available) during the `make`.

If you could tell about it in the readme, it might prevent other people from facing the same issue :-)

**Comment by brandenburg** [comment]
Thanks for the suggestion. I’m happy to merge patches that improve the documentation or the code. Please send a pull request.

Thanks,
Björn
